name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@3

    - name: Run build commands
      run: |
        echo "Buildind the project...."
    